language: node_js

node_js:
  - "5"

sudo: false

addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

before_script:
  - npm install -g cordova less

script: bash -ex .travis-ci.sh

env:
  - OPAM_SWITCH=4.03.0

cache:
  directories:
  - $HOME/.opam

git:
  depth: 1
